### ISSUE TITLE
I guess this is not working

### ISSUE THREAD

**Issue by daUnknownCoder** [VortexCoyote/hyprfocus#14]
https://github.com/VortexCoyote/hyprfocus/assets/84800625/92fb7234-12cf-4c60-a2e0-1fb7f2a74019

and can u pls provide your hyprland.conf? coz when u switch active windows, your cursor doesnt move to the center idk mine centers always for
```hypr
# Move focus with s + arrow keys
binde = $s, left, movefocus, l
binde = $s, right, movefocus, r
binde = $s, up, movefocus, u
binde = $s, down, movefocus, d
```

so what do u do?

```bash
hyprpm reload hyprfocus -n -v
[v] version returned: Hyprland, built from branch main at commit 91e8c428431deac1e5eb8e537f002ab960777174 dirty (hyprpm: don't update headers if they are up-to-date, only recompile).
Date: Mon Jan 29 16:00:31 2024
Tag: v0.34.0-80-g91e8c428

flags: (if any)


[v] parsed commit 91e8c428431deac1e5eb8e537f002ab960777174 at branch main
✔ Ensuring plugin load state
✔ Unloaded hycov
✔ Plugin load state ensured
```

so idk whats the problem it loads but doesnt work

**Comment by katter** [comment]
Works a charm for me on hyprland 0.35, compiled the new way as per hyprland wiki (Reads like you did the same).
Did you by any chance omit to add the plugin config to your hyprland.conf? ( https://github.com/VortexCoyote/hyprfocus?tab=readme-ov-file#getting-started )
For the mousepointer bit: When I change the focus by moving the mouse, it's like in the videos, when changing focus with the keyboard, the mousepointer ends up centered

**Comment by daUnknownCoder** [comment]
works on hyprland 0.35 it didnt use to work on 0.34... thanks anyway and

> when changing focus with the keyboard, the mousepointer ends up centered

for those things @katter : use 
```hypr
input {
    follow_mouse = 2
    touchpad {
        tap-to-click = 1
    }
}
```
 --> to click to change focus of window instead of hover -> [#1354](https://github.com/hyprwm/Hyprland/issues/1354#issuecomment-1426997787)


```hypr
general {
    no_cursor_warps = true
}
```
--> to not go to the middle of the window when changing them -> [#1354](https://github.com/hyprwm/Hyprland/issues/1354#issuecomment-1412703340)
