### ISSUE TITLE
[Feature Request] Dim animation

### ISSUE THREAD

**Issue by donovanglover** [VortexCoyote/hyprfocus#5]
I like the `dim_inactive` feature of Hyprland but keeping it on all the time makes it difficult to reference inactive windows. Would it be possible to temporarily dim inactive windows with hyprfocus?

**Comment by VortexCoyote** [comment]
i would need more information on exactly what you mean. there already is the flash animation, but i assume that it's not what you mean

**Comment by donovanglover** [comment]
Let's say you have 3 windows A, B and C. When you change focus from A to B, windows A and C are dimmed and B stays the same. Basically `dim_inactive` except it automatically turns on and off

**Comment by VortexCoyote** [comment]
what would determine whether it turns on or off?

**Comment by donovanglover** [comment]
Turns on when changing focus and turns off after X milliseconds of inactivity (no focus changes)

**Comment by donovanglover** [comment]
Closing since I wrote [hyprland-autodim](https://github.com/donovanglover/hyprland-autodim) to do what I wanted
